WARNING: Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\py-projects\test\module12\tests_12_4.py", line 80, in test_run
    runner = Runner(2321)
             ^^^^^^^^^^^^
  File "D:\py-projects\test\module12\tests_12_4.py", line 17, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
WARNING: Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\py-projects\test\module12\tests_12_4.py", line 68, in test_walk
    runner = Runner('Alex', -5)
             ^^^^^^^^^^^^^^^^^^
  File "D:\py-projects\test\module12\tests_12_4.py", line 22, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
